### ISSUE TITLE
error in main.py-> line 106/107 

### ISSUE THREAD

**Issue by SimonPig** [jiangzhongshi/SurfaceNetworks#5]
'Di.append(samples[ind]['Di'])
DiA.append(samples[ind]['DiA'])':
KeyError:'Di'

i looked into the samples and saw no elements named 'Di' nor 'DiA'...
should them be 'V' and 'F' instead?

thank u ;)

**Comment by jiangzhongshi** [comment]
Hi Simon, 

Which data are you using? MNIST or SpatioTemporal?

Best,
Zhongshi

**Comment by SimonPig** [comment]
Thx for your rply,
i only used MINST so far, and not quite get what Di/DiA indicates here
Best regards,
H

**Comment by jiangzhongshi** [comment]
Hi,

Firstly, Di/DiA means Dirac operator on meshes, you can refer to the paper for more details about it.
For the MeshMNIST dataset, indeed there's no Di entry yet, and you need to run this first to generate them. Sorry for the confusion. I should try to add them to the dataset at some point. https://github.com/jiangzhongshi/SurfaceNetworks/blob/dev/src/mesh_mnist/add_laplacian.py

On the other hand, for other tasks `Di/DiA` are already there.

Best,
Zhongshi
